# Generated by Django 3.2.4 on 2021-08-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20210709_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informacion', models.TextField(max_length=500, null=True, verbose_name='Informacion del desarrollador')),
                ('imagen', models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografía del desarrollador')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nosotro',
                'verbose_name_plural': 'Nosotros',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='ventas',
            name='descripcion',
            field=models.TextField(max_length=500, null=True, verbose_name='Descripcion del producto'),
        ),
    ]
