# Generated by Django 3.2.4 on 2021-08-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_nosotros_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioContacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('usuario', models.TextField(verbose_name='Usuario')),
                ('mensaje', models.TextField(verbose_name='Comentario')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
            ],
            options={
                'verbose_name': 'Comentario Contacto',
                'verbose_name_plural': 'Comentarios Contactos',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='nosotros',
            name='nombre',
            field=models.CharField(max_length=80, null=True, verbose_name='Nombre del desarrollador'),
        ),
    ]
