# Generated by Django 3.2.4 on 2021-08-24 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_auto_20210823_2226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentariocontacto',
            options={'ordering': ['-created'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.RenameField(
            model_name='comentariocontacto',
            old_name='mensaje',
            new_name='coment',
        ),
    ]
