# Generated by Django 3.2.4 on 2021-08-24 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_alter_comentariocontacto_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentariocontacto',
            old_name='coment',
            new_name='mensaje',
        ),
    ]
